In [1]:
# Numpy: Number + Python
# main object: ndarray

In [1]:
import numpy
numpy.array

<function numpy.array>

In [2]:
import numpy as np

my_list = [10,20,30]
np.array(my_list)

array([10, 20, 30])

In [3]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# ndarray.shape: gives the dimension of the array
# ndarray.dtype: an object describing the type of the elements in an array
# ndarray.reshape: returns an array containing the data with a new shape

In [5]:
my_list = [10,20,30]

arr = np.array(my_list)
print(arr.dtype)
print(arr.shape)

int64
(3,)


In [7]:
twod_array=np.array(list_of_lists)
print(twod_array.shape)

(3, 3)


In [10]:
# arange
np.arange(0,10)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
# in this the type is float64 hence the 0.
np.zeros((2,3))
# if we want the type to be int64 we can:
# np.zeros((2,3), dtype=int)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# linspace: return evenly spaced numbers over a specified interval
# linspace(start, stop, num=50, endpoint=True, retstep=False)
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])