In [1]:
# Numpy: Number + Python
# main object: ndarray

In [1]:
import numpy
numpy.array

<function numpy.array>

In [2]:
import numpy as np

my_list = [10,20,30]
np.array(my_list)

array([10, 20, 30])

In [3]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# ndarray.shape: gives the dimension of the array
# ndarray.dtype: an object describing the type of the elements in an array
# ndarray.reshape: returns an array containing the data with a new shape

In [5]:
my_list = [10,20,30]

arr = np.array(my_list)
print(arr.dtype)
print(arr.shape)

int64
(3,)


In [7]:
twod_array=np.array(list_of_lists)
print(twod_array.shape)

(3, 3)


In [10]:
# arange
np.arange(0,10)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
# in this the type is float64 hence the 0.
np.zeros((2,3))
# if we want the type to be int64 we can:
# np.zeros((2,3), dtype=int)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# linspace: return evenly spaced numbers over a specified interval
# linspace(start, stop, num=50, endpoint=True, retstep=False)
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

# Why pandas
1. Intrinsic Data Alignment
2. Data Standardization Functions
3. Data Operation Functions
4. Functions for handling missing data
5. Data Structures Handling Major Use Cases

# Features of Pandas:
1. Powerful Data Structure
2. Fast and Efficient Data Wrangling
3. Easy Data Aggregation and Transformation
4. Tools for reading/writing data
5. Intelligent and Automated Data Alignment
6. High Performance Merging and Joining of Data Sets

# Pandas Data Strucutres:
1. Series:
   * One-dimensional labeled array
   * Supports Multiple Data Types
2. Data Frame:
   * Two-dimensional labeled array
   * Supports Multiple Data Types
   * Input can be series
   * Input can be other data frame
3. Panel:
   * Three-dimensional labled array
   * Supports multiple data types
   * Item-> axis 0
   * Major axis -> rows
   * Minor axis -> columns
4. Panel 4D(experimental):
   * Four-dimensional labeled array
   * Supports multiple data types
   * Labels -> axis 0
   * Items -> axis 1
   * Major axis -> rows
   * Minor axis -> columns

# Pandas Series:

In [2]:
import pandas as pd

my_list = [10,20,30]
ser = pd.Series(my_list)

print(ser)
print(ser.index)
print(ser.values)

0    10
1    20
2    30
dtype: int64
RangeIndex(start=0, stop=3, step=1)
[10 20 30]


In [3]:
# Creating a series from numpy array
import numpy as np
import pandas as pd

index = ['a','b','c']
arr = np.array([10,20,30])

pd.Series(data=arr, index=index)

a    10
b    20
c    30
dtype: int64

In [4]:
# Creating a series from dictionary
import pandas as pd

d= {'a':10, 'b':20, 'c':30}
pd.Series(d)

a    10
b    20
c    30
dtype: int64