In [1]:
# Numpy: Number + Python
# main object: ndarray

In [1]:
import numpy
numpy.array

<function numpy.array>

In [2]:
import numpy as np

my_list = [10,20,30]
np.array(my_list)

array([10, 20, 30])

In [3]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# ndarray.shape: gives the dimension of the array
# ndarray.dtype: an object describing the type of the elements in an array
# ndarray.reshape: returns an array containing the data with a new shape

In [5]:
my_list = [10,20,30]

arr = np.array(my_list)
print(arr.dtype)
print(arr.shape)

int64
(3,)


In [7]:
twod_array=np.array(list_of_lists)
print(twod_array.shape)

(3, 3)


In [10]:
# arange
np.arange(0,10)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
# in this the type is float64 hence the 0.
np.zeros((2,3))
# if we want the type to be int64 we can:
# np.zeros((2,3), dtype=int)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# linspace: return evenly spaced numbers over a specified interval
# linspace(start, stop, num=50, endpoint=True, retstep=False)
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

# Why pandas
1. Intrinsic Data Alignment
2. Data Standardization Functions
3. Data Operation Functions
4. Functions for handling missing data
5. Data Structures Handling Major Use Cases

# Features of Pandas:
1. Powerful Data Structure
2. Fast and Efficient Data Wrangling
3. Easy Data Aggregation and Transformation
4. Tools for reading/writing data
5. Intelligent and Automated Data Alignment
6. High Performance Merging and Joining of Data Sets

# Pandas Data Strucutres:
1. Series:
   * One-dimensional labeled array
   * Supports Multiple Data Types
2. Data Frame:
   * Two-dimensional labeled array
   * Supports Multiple Data Types
   * Input can be series
   * Input can be other data frame
3. Panel:
   * Three-dimensional labled array
   * Supports multiple data types
   * Item-> axis 0
   * Major axis -> rows
   * Minor axis -> columns
4. Panel 4D(experimental):
   * Four-dimensional labeled array
   * Supports multiple data types
   * Labels -> axis 0
   * Items -> axis 1
   * Major axis -> rows
   * Minor axis -> columns

# Pandas Series:

In [2]:
import pandas as pd

my_list = [10,20,30]
ser = pd.Series(my_list)

print(ser)
print(ser.index)
print(ser.values)

0    10
1    20
2    30
dtype: int64
RangeIndex(start=0, stop=3, step=1)
[10 20 30]


In [3]:
# Creating a series from numpy array
import numpy as np
import pandas as pd

index = ['a','b','c']
arr = np.array([10,20,30])

pd.Series(data=arr, index=index)

a    10
b    20
c    30
dtype: int64

In [4]:
# Creating a series from dictionary
import pandas as pd

d= {'a':10, 'b':20, 'c':30}
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [6]:
# Using index in series
import pandas as pd
ser1 = pd.Series(data=[1,2,3,4], index=['USA', 'UK', 'India', 'Japan'])
ser2 = pd.Series(data=[1,2,3,4], index=['USA', 'UK', 'Italy', 'Japan'])

print(ser1['USA'])

1


In [7]:
print(ser1+ser2)

India    NaN
Italy    NaN
Japan    8.0
UK       4.0
USA      2.0
dtype: float64


In [2]:
# Data Frames:
import pandas as pd
import numpy as np

df = pd.DataFrame([[1,2,3],
       [4,5,6],
       [7,8,9]])
df

,0,1,2
0,1,2,3
1,4,5,6
2,7,8,9


In [3]:
type(df)

pandas.core.frame.DataFrame

In [4]:
print(df.shape)
print(df.index)

(3, 3)
RangeIndex(start=0, stop=3, step=1)


In [5]:
df2 = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9], [10,11,12]],
                  index=['a','b','c','d'], columns=['x','y','z'])
df2

,x,y,z
a,1,2,3
b,4,5,6
c,7,8,9
d,10,11,12


# Weather Dataset Project

In [7]:
weather_df = pd.read_csv('weather_2012.csv')

print('Shape: ', weather_df.shape)
print('Index: ', weather_df.index)

Shape:  (8784, 8)
Index:  RangeIndex(start=0, stop=8784, step=1)


In [8]:
weather_df['Date/Time'].head()

0    2012-01-01 00:00:00
1    2012-01-01 01:00:00
2    2012-01-01 02:00:00
3    2012-01-01 03:00:00
4    2012-01-01 04:00:00
Name: Date/Time, dtype: object

In [9]:
weather_df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog


In [10]:
type(weather_df['Date/Time'])

pandas.core.series.Series

In [11]:
# Let's convert the Date/Time column datatype from object to timestamp so that we can access the month directly using dt.month
weather_df['Date/Time'] = pd.to_datetime(weather_df['Date/Time'])
weather_df['Date/Time'].head()

0   2012-01-01 00:00:00
1   2012-01-01 01:00:00
2   2012-01-01 02:00:00
3   2012-01-01 03:00:00
4   2012-01-01 04:00:00
Name: Date/Time, dtype: datetime64[ns]

In [12]:
# How to analyze data frames
# .info: Provides a summary of a DataFrame: rows, columns, data types of columns

weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype         
---  ------              --------------  -----         
 0   Date/Time           8784 non-null   datetime64[ns]
 1   Temp (C)            8784 non-null   float64       
 2   Dew Point Temp (C)  8784 non-null   float64       
 3   Rel Hum (%)         8784 non-null   int64         
 4   Wind Spd (km/h)     8784 non-null   int64         
 5   Visibility (km)     8784 non-null   float64       
 6   Stn Press (kPa)     8784 non-null   float64       
 7   Weather             8784 non-null   object        
dtypes: datetime64[ns](1), float64(4), int64(2), object(1)
memory usage: 549.1+ KB


In [14]:
# .head: returns first 5 also can give parameter
weather_df.head(10)

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog
5,2012-01-01 05:00:00,-1.4,-3.3,87,9,6.4,101.27,Fog
6,2012-01-01 06:00:00,-1.5,-3.1,89,7,6.4,101.29,Fog
7,2012-01-01 07:00:00,-1.4,-3.6,85,7,8.0,101.26,Fog
8,2012-01-01 08:00:00,-1.4,-3.6,85,9,8.0,101.23,Fog
9,2012-01-01 09:00:00,-1.3,-3.1,88,15,4.0,101.20,Fog


In [16]:
# .tail: returns the last 5 also can give parameter
weather_df.tail()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow


In [17]:
weather_df.tail(10)

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
8774,2012-12-31 14:00:00,-3.4,-5.7,84,6,11.3,100.57,Snow
8775,2012-12-31 15:00:00,-2.3,-4.6,84,9,9.7,100.47,Snow
8776,2012-12-31 16:00:00,-1.4,-4.0,82,13,12.9,100.40,Snow
8777,2012-12-31 17:00:00,-1.1,-3.3,85,19,9.7,100.30,Snow
8778,2012-12-31 18:00:00,-1.3,-3.1,88,17,9.7,100.19,Snow
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow


In [22]:
# .index: This attribute provides the index of the data frame
weather_df.index

RangeIndex(start=0, stop=8784, step=1)

In [24]:
# .unique: The name itself is self-sufficient
weather_df['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 

In [25]:
# .nunique: The number of unique elements. ignores na values 
weather_df['Weather'].nunique()

50

In [26]:
# .value_counts: Understand from the example
weather_df['Weather'].value_counts()

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                

In [29]:
weather_df['Weather'].value_counts()[2]

/var/folders/8t/fh2nryhx7hvfc36kndxf3gw40000gn/T/ipykernel_62554/728081491.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  weather_df['Weather'].value_counts()[2]


1728

In [30]:
weather_df['Weather'].value_counts()['Rain']

306

# Data Manipulation/Transformation

## Selection(Part 1)

In [32]:
col = weather_df['Weather']
print(type(col))
col.head()

<class 'pandas.core.series.Series'>


0                     Fog
1                     Fog
2    Freezing Drizzle,Fog
3    Freezing Drizzle,Fog
4                     Fog
Name: Weather, dtype: object

In [34]:
two_cols = weather_df[['Weather','Temp (C)']]

print(type(two_cols))
two_cols.head()

<class 'pandas.core.frame.DataFrame'>


,Weather,Temp (C)
0,Fog,-1.8
1,Fog,-1.8
2,"Freezing Drizzle,Fog",-1.8
3,"Freezing Drizzle,Fog",-1.5
4,Fog,-1.5


In [37]:
# When working with Pandas always try to ignore slicing instead use .loc and .iloc
weather_df.loc[0:5, ['Visibility (km)', 'Rel Hum (%)']]

,Visibility (km),Rel Hum (%)
0,8.0,86
1,8.0,87
2,4.0,89
3,4.0,88
4,4.8,88
5,6.4,87


In [38]:
weather_df[['Visibility (km)', 'Rel Hum (%)']].loc[0:5]

,Visibility (km),Rel Hum (%)
0,8.0,86
1,8.0,87
2,4.0,89
3,4.0,88
4,4.8,88
5,6.4,87


In [39]:
weather_df[['Visibility (km)', 'Rel Hum (%)']].iloc[0:5]

,Visibility (km),Rel Hum (%)
0,8.0,86
1,8.0,87
2,4.0,89
3,4.0,88
4,4.8,88


# Filtering

In [40]:
weather_df['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 

In [41]:
snowed_filter = weather_df['Weather'].str.lower().str.contains('snow')
weather_df[snowed_filter]

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
41,2012-01-02 17:00:00,-2.1,-9.5,57,22,25.0,99.66,Snow Showers
44,2012-01-02 20:00:00,-5.6,-13.4,54,24,25.0,100.07,Snow Showers
45,2012-01-02 21:00:00,-5.8,-12.8,58,26,25.0,100.15,Snow Showers
47,2012-01-02 23:00:00,-7.4,-14.1,59,17,19.3,100.27,Snow Showers
48,2012-01-03 00:00:00,-9.0,-16.0,57,28,25.0,100.35,Snow Showers
...,...,...,...,...,...,...,...,...
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow


In [42]:
weather_df['Weather'].iloc[8782]

'Snow'

In [43]:
speed_filter = (weather_df['Wind Spd (km/h)'] > 24) & (weather_df['Visibility (km)'] == 25)
weather_df[speed_filter]

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
23,2012-01-01 23:00:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,2012-01-02 00:00:00,5.2,1.5,77,35,25.0,99.26,Rain Showers
25,2012-01-02 01:00:00,4.6,0.0,72,39,25.0,99.26,Cloudy
26,2012-01-02 02:00:00,3.9,-0.9,71,32,25.0,99.26,Mostly Cloudy
27,2012-01-02 03:00:00,3.7,-1.5,69,33,25.0,99.30,Mostly Cloudy
...,...,...,...,...,...,...,...,...
8705,2012-12-28 17:00:00,-8.6,-12.0,76,26,25.0,101.34,Mainly Clear
8753,2012-12-30 17:00:00,-12.1,-15.8,74,28,25.0,101.26,Mainly Clear
8755,2012-12-30 19:00:00,-13.4,-16.5,77,26,25.0,101.47,Mainly Clear
8759,2012-12-30 23:00:00,-12.1,-15.1,78,28,25.0,101.52,Mostly Cloudy


# Series Operations

In [46]:
weather_df['Wind Spd (km/h)'].head()

0    4
1    4
2    7
3    6
4    7
Name: Wind Spd (km/h), dtype: int64

In [45]:
weather_df['Wind Spd (km/h)'].head() + 10

0    14
1    14
2    17
3    16
4    17
Name: Wind Spd (km/h), dtype: int64

In [48]:
weather_df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog


In [49]:
weather_df['new_temp_col'] = weather_df['Temp (C)'] + weather_df['Dew Point Temp (C)']
weather_df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather,new_temp_col
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog,-5.7
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog,-5.5
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog",-5.2
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog",-4.7
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog,-4.8


In [50]:
# .apply : understand from the example

def times2(value):
    return value * 2

t2 = weather_df['Visibility (km)'].apply(times2)
t2.head()

0    16.0
1    16.0
2     8.0
3     8.0
4     9.6
Name: Visibility (km), dtype: float64

In [51]:
weather_df['Visibility (km)'].describe()

count    8784.000000
mean       27.664447
std        12.622688
min         0.200000
25%        24.100000
50%        25.000000
75%        25.000000
max        48.300000
Name: Visibility (km), dtype: float64

In [63]:
# Adding/Updating columns
visibility_in_meter = weather_df['Visibility (km)'] * 1000
weather_df['Visibility (m)'] = visibility_in_meter

weather_df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather,new_temp_col,Visibility (m)
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog,-5.7,8000.0
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog,-5.5,8000.0
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog",-5.2,4000.0
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog",-4.7,4000.0
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog,-4.8,4800.0


In [64]:
weather_df.rename(columns={'Visibility (m)':'Visibility (meters)',
                          'Visibility (km)':'Visibility (kilometers)'}, inplace = True)
weather_df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (kilometers),Stn Press (kPa),Weather,new_temp_col,Visibility (meters)
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog,-5.7,8000.0
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog,-5.5,8000.0
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog",-5.2,4000.0
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog",-4.7,4000.0
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog,-4.8,4800.0


In [65]:
weather_df.rename(columns={'Visibility (kilometers)':'Visibility (km)'}, inplace=True)
weather_df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather,new_temp_col,Visibility (meters)
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog,-5.7,8000.0
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog,-5.5,8000.0
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog",-5.2,4000.0
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog",-4.7,4000.0
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog,-4.8,4800.0


In [66]:
weather_df.drop(labels = ['Visibility (meters)'], axis=1)
weather_df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather,new_temp_col,Visibility (meters)
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog,-5.7,8000.0
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog,-5.5,8000.0
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog",-5.2,4000.0
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog",-4.7,4000.0
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog,-4.8,4800.0


In [67]:
# Sorting
sorted_by_temp = weather_df.sort_values('Temp (C)', ascending=False)
sorted_by_temp.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather,new_temp_col,Visibility (meters)
4695,2012-07-14 15:00:00,33.0,16.8,38,22,48.3,101.31,Mainly Clear,49.8,48300.0
4143,2012-06-21 15:00:00,33.0,19.0,44,24,24.1,100.20,Mainly Clear,52.0,24100.0
4696,2012-07-14 16:00:00,32.9,15.3,35,24,48.3,101.26,Mainly Clear,48.2,48300.0
5199,2012-08-04 15:00:00,32.8,18.8,44,17,24.1,101.39,Clear,51.6,24100.0
4694,2012-07-14 14:00:00,32.7,15.3,35,28,48.3,101.35,Mainly Clear,48.0,48300.0


In [68]:
weather_df = weather_df.drop(['Visibility (meters)'], axis = 1)
weather_df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather,new_temp_col
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog,-5.7
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog,-5.5
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog",-5.2
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog",-4.7
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog,-4.8


In [ ]:
# Which were the top 10 hottest values and their count
sorted_value_count = weather_df['Temp (C)'].value_counts().sort_values(ascending = False)
sorted_value_count